// Code generated by Arduino IoT Cloud, DO NOT EDIT.

#include <ArduinoIoTCloud.h>
#include <Arduino_ConnectionHandler.h>


const char THING_ID[]           = "d7fba9f8-4641-4580-8954-554d83766a01";
const char DEVICE_LOGIN_NAME[]  = "8162e931-02aa-44a1-ad88-8d1304857cf0";

const char SSID[]               = SECRET_SSID;    // Network SSID (name)
const char PASS[]               = SECRET_PASS;    // Network password (use for WPA, or use as key for WEP)
const char DEVICE_KEY[]  = SECRET_DEVICE_KEY;    // Secret device password

void onBombaChange();
void onIrrigChange();
void onSensorChange();

bool bomba;
bool irrig;
float sensor;

void initProperties(){

  ArduinoCloud.setBoardId(DEVICE_LOGIN_NAME);
  ArduinoCloud.setSecretDeviceKey(DEVICE_KEY);
  ArduinoCloud.setThingId(THING_ID);
  ArduinoCloud.addProperty(bomba, READWRITE, ON_CHANGE, onBombaChange);
  ArduinoCloud.addProperty(irrig, READWRITE, ON_CHANGE, onIrrigChange);
  ArduinoCloud.addProperty(sensor, READWRITE, 5 * SECONDS, onSensorChange);

}

WiFiConnectionHandler ArduinoIoTPreferredConnection(SSID, PASS);
